@           |----------------------------------|
gBirchSpeech_Welcome:: @ 81C6D78
	.string "Oh hi, I didn't see you there.\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "While my name is BIRCH, not OAK,\n"
	.string "everyone calls me the POKéMON\l"
	.string "PROFESSOR anyway.\p$"

gBirchSpeech_ThisIsPokemon:: @ 81C6DF8
	.string "This is what we call a “MEWTWO.”$"

gBirchSpeech_WorldInhabitedByPokemon:: @ 81C6E1A
	.string "It's a great POKéMON, but you\n"
	.string "won't be getting one for a while.\p"
	.string "This world is widely inhabited by\n"
	.string "POKéMON, big and small.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "(You'll be doing that a lot.)\p"
	.string "But despite our closeness, we\n"
	.string "haven't even figured out how to\l"
	.string "capture them in POKéBALLs!\p"
	.string "So, you're going to have to do it\n"
	.string "the old fashioned way:\p"
	.string "By fighting a lot of POKéMON and\n"
	.string "hoping they drop eggs!\p"
	.string "Anyway...\p$"

gBirchSpeech_AndYouAre:: @ 81C6FCB
	.string "Who the heck are you?$"

gBirchSpeech_AreYouBoyOrGirl:: @ 81C6FD8
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gBirchSpeech_WhatsYourName:: @ 81C6FFA
	.string "All right.\n"
	.string "What's your name?$"

gBirchSpeech_SoItsPlayer:: @ 81C7017
	.string "So it's {PLAYER}{KUN}?$"

gBirchSpeech_AhOkayYouArePlayer:: @ 81C7025
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I totally knew that!\p"
	.string "What's that? MEWTWO has changed?\p"
	.string "Wow, more mysteries before our\n"
	.string "very eyes!\p$"

gBirchSpeech_AreYouReady:: @ 81C7074
	.string "All right, are you ready?\p"
	.string "Your very own gacha-style\n"
	.string "adventure is about to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where eggs,\l"
	.string "adventure, and nonsense await!\p"
	.string "I guess I'll be expecting you\n"
	.string "later. Come see me in my POKéMON\l"
	.string "LAB when you're all set up!\p$"
