gBirchSpeech_Welcome:: @ 81C6D78
	.string "Hello, and sorry to keep you\n"
	.string "waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH, not OAK,\p"
	.string "but everyone calls me the POKéMON\n"
	.string "PROFESSOR anyway.\p$"

gBirchSpeech_ThisIsPokemon:: @ 81C6DF8
	.string "This is what we call a “MEWTWO.”$"

gBirchSpeech_WorldInhabitedByPokemon:: @ 81C6E1A
	.string "It's a great POKéMON, but you\n"
	.string "won't be getting one for a while.\p"
	@.string "This world is widely inhabited by\n"
	@.string "POKéMON, big and small.\p"
	@.string "We humans live alongside POKéMON,\n"
	@.string "at times as friendly playmates, and\l"
	@.string "at times as cooperative workmates.\p"
	@.string "And sometimes, we band together\n"
	@.string "and battle others like us.\p"
	@.string "(You'll be doing that a lot.)\p"
	@.string "But despite our closeness, we don't\n"
	@.string "know everything about POKéMON.\p"
	@.string "In fact, there are many, many\n"
	@.string "secrets surrounding POKéMON.\p"
	@.string "To unravel POKéMON mysteries,\n"
	@.string "I've been undertaking research.\l"
	@.string "That's what I do, since I'm the\n"
	@.string "POKéMON PROFESSOR.\p$"
	.string "Blah blah, let's move on.\p$"

gBirchSpeech_AndYouAre:: @ 81C6FCB
	.string "And you are?$"

gBirchSpeech_AreYouBoyOrGirl:: @ 81C6FD8
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gBirchSpeech_WhatsYourName:: @ 81C6FFA
	.string "All right.\n"
	.string "What's your name?$"

gBirchSpeech_SoItsPlayer:: @ 81C7017
	.string "So it's {PLAYER}{KUN}?$"

gBirchSpeech_AhOkayYouArePlayer:: @ 81C7025
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "What’s that? MEWTWO has changed?\p"
	.string "Wow, more mysteries before our\n"
	.string "very eyes!\p$"

gBirchSpeech_AreYouReady:: @ 81C7074
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p$"
